// <auto-generated />
using System;
using FlightKS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightKS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514213434_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking_status", new[] { "upcoming", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cabin_class", new[] { "economy", "premium_economy", "business", "first" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notif_type", new[] { "booking", "alert", "reminder", "promo" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "passenger_type", new[] { "adult", "child", "infant" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "seat_side", new[] { "window", "middle", "aisle" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trip_type", new[] { "one_way", "round_trip" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightKS.Models.Entities.Airport", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(3)")
                        .HasColumnName("code");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("timezone");

                    b.HasKey("Code")
                        .HasName("pk_airports");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_fare");

                    b.Property<DateTime>("BookedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Cabin")
                        .HasColumnType("cabin_class")
                        .HasColumnName("cabin");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flight_id");

                    b.Property<short>("PassengerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("passenger_count");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("booking_status")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'upcoming'::booking_status");

                    b.Property<decimal>("TaxesFees")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("taxes_fees");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_price");

                    b.Property<int>("TripType")
                        .HasColumnType("trip_type")
                        .HasColumnName("trip_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("ix_bookings_flight_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_reference");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookings_user_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.BookingPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<decimal>("Fare")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fare");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FrequentFlyerNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frequent_flyer_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<int>("PassengerType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("passenger_type")
                        .HasColumnName("passenger_type")
                        .HasDefaultValueSql("'adult'::passenger_type");

                    b.Property<DateOnly>("PassportExpiry")
                        .HasColumnType("date")
                        .HasColumnName("passport_expiry");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("passport_number");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("seat_number");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text")
                        .HasColumnName("special_requests");

                    b.HasKey("Id")
                        .HasName("pk_booking_passengers");

                    b.HasIndex("BookingId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_passengers_booking_id_seat_number")
                        .HasFilter("seat_number IS NOT NULL");

                    b.ToTable("booking_passengers", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Flight", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("airline");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_time");

                    b.Property<bool>("BaggageIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("baggage_included");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_time");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("destination");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("flight_number");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("origin");

                    b.Property<bool>("Refundable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("refundable");

                    b.Property<short>("Stops")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("stops");

                    b.HasKey("Id")
                        .HasName("pk_flights");

                    b.HasIndex("Destination")
                        .HasDatabaseName("ix_flights_destination");

                    b.HasIndex("Origin")
                        .HasDatabaseName("ix_flights_origin");

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.FlightPrice", b =>
                {
                    b.Property<string>("FlightId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flight_id");

                    b.Property<int>("Cabin")
                        .HasColumnType("cabin_class")
                        .HasColumnName("cabin");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<short>("TotalSeats")
                        .HasColumnType("smallint")
                        .HasColumnName("total_seats");

                    b.HasKey("FlightId", "Cabin")
                        .HasName("pk_flight_prices");

                    b.ToTable("flight_prices", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<bool>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("read");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("notif_type")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.PriceAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("Cabin")
                        .HasColumnType("cabin_class")
                        .HasColumnName("cabin");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("current_price");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("date")
                        .HasColumnName("date_from");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("date")
                        .HasColumnName("date_to");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("destination");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("origin");

                    b.Property<decimal>("TargetPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("target_price");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_price_alerts");

                    b.HasIndex("Destination")
                        .HasDatabaseName("ix_price_alerts_destination");

                    b.HasIndex("Origin")
                        .HasDatabaseName("ix_price_alerts_origin");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_price_alerts_user_id");

                    b.ToTable("price_alerts", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.SavedFlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("Adults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("adults");

                    b.Property<int>("Cabin")
                        .HasColumnType("cabin_class")
                        .HasColumnName("cabin");

                    b.Property<DateOnly>("DepartDate")
                        .HasColumnType("date")
                        .HasColumnName("depart_date");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flight_id");

                    b.Property<decimal>("PriceAtSave")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_at_save");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_flights");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("ix_saved_flights_flight_id");

                    b.HasIndex("UserId", "FlightId", "Cabin", "DepartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_flights_user_id_flight_id_cabin_depart_date");

                    b.ToTable("saved_flights", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.SavedTraveler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<DateOnly?>("PassportExpiry")
                        .HasColumnType("date")
                        .HasColumnName("passport_expiry");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("passport_number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_travelers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_saved_travelers_user_id");

                    b.ToTable("saved_travelers", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("Adults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("adults");

                    b.Property<int>("Cabin")
                        .HasColumnType("cabin_class")
                        .HasColumnName("cabin");

                    b.Property<DateOnly>("DepartDate")
                        .HasColumnType("date")
                        .HasColumnName("depart_date");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("destination");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("origin");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.Property<DateTime>("SearchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("TripType")
                        .HasColumnType("trip_type")
                        .HasColumnName("trip_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_search_history");

                    b.HasIndex("Destination")
                        .HasDatabaseName("ix_search_history_destination");

                    b.HasIndex("Origin")
                        .HasDatabaseName("ix_search_history_origin");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_search_history_user_id");

                    b.ToTable("search_history", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.UserLoyalty", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("FrequentFlyerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frequent_flyer_number");

                    b.Property<string>("FrequentFlyerProgram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("frequent_flyer_program");

                    b.HasKey("UserId")
                        .HasName("pk_user_loyalty");

                    b.ToTable("user_loyalty", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.UserPassport", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("passport_number");

                    b.HasKey("UserId")
                        .HasName("pk_user_passports");

                    b.ToTable("user_passports", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_notifications");

                    b.Property<int?>("PreferredCabin")
                        .HasColumnType("cabin_class")
                        .HasColumnName("preferred_cabin");

                    b.Property<string>("PreferredCurrency")
                        .HasColumnType("char(3)")
                        .HasColumnName("preferred_currency");

                    b.Property<string>("PreferredMeal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("preferred_meal");

                    b.Property<int?>("PreferredSeat")
                        .HasColumnType("seat_side")
                        .HasColumnName("preferred_seat");

                    b.Property<bool>("SmsNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sms_notifications");

                    b.HasKey("UserId")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Booking", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_flights_flight_id");

                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_user_id");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.BookingPassenger", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_passengers_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Flight", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("Destination")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flights_airports_destination");

                    b.HasOne("FlightKS.Models.Entities.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("Origin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_flights_airports_origin");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.FlightPrice", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.Flight", "Flight")
                        .WithMany("Prices")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_flight_prices_flights_flight_id");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Notification", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.PriceAlert", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("Destination")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_alerts_airports_destination");

                    b.HasOne("FlightKS.Models.Entities.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("Origin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_alerts_airports_origin");

                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithMany("PriceAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_alerts_users_user_id");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.SavedFlight", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_saved_flights_flights_flight_id");

                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithMany("SavedFlights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_flights_users_user_id");

                    b.Navigation("Flight");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.SavedTraveler", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithMany("SavedTravelers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_travelers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.SearchHistory", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.Airport", "DestinationAirport")
                        .WithMany()
                        .HasForeignKey("Destination")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_search_history_airports_destination");

                    b.HasOne("FlightKS.Models.Entities.Airport", "OriginAirport")
                        .WithMany()
                        .HasForeignKey("Origin")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_search_history_airports_origin");

                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithMany("SearchHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_search_history_users_user_id");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.UserLoyalty", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithOne("Loyalty")
                        .HasForeignKey("FlightKS.Models.Entities.UserLoyalty", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_loyalty_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.UserPassport", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithOne("Passport")
                        .HasForeignKey("FlightKS.Models.Entities.UserPassport", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_passports_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.UserPreferences", b =>
                {
                    b.HasOne("FlightKS.Models.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("FlightKS.Models.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Booking", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.Flight", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("FlightKS.Models.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Loyalty");

                    b.Navigation("Notifications");

                    b.Navigation("Passport");

                    b.Navigation("Preferences");

                    b.Navigation("PriceAlerts");

                    b.Navigation("SavedFlights");

                    b.Navigation("SavedTravelers");

                    b.Navigation("SearchHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
